### ISSUE TITLE
Add a customized favicon 

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#12]

**Comment by makromikro** [comment]
@iarobinson is this about creating an icon for our website?

**Comment by iarobinson** [comment]
Yea. Favicons are these guys:

<img width="462" alt="screen shot 2019-02-16 at 9 04 40 pm" src="https://user-images.githubusercontent.com/7991933/52908636-9323eb80-322e-11e9-805a-24ea4ae55519.png">

It should be a pretty simple project. If you need the actual favicon image, I can make it. Otherwise feel free to make it yourself. 
You Rock!

**Comment by makromikro** [comment]
Done! 
![image](https://user-images.githubusercontent.com/46354335/52909188-d475c480-3249-11e9-8863-3ea71b66ef93.png)

**Comment by iarobinson** [comment]
Nicely done @makromikro . I'll close this issue now.
