### ISSUE TITLE
Add a link to your collaborator page

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#18]
<img width="722" alt="screen shot 2019-02-12 at 11 19 05 pm" src="https://user-images.githubusercontent.com/7991933/52693860-cad42000-2f1c-11e9-9d58-ba87b9dbd71d.png">

**Comment by delagulater88** [comment]
i think i modeled this in the index.html file...i updated my name from my github username to my actual name and i  added the link to my collaborator page also....but it doesnt seem to have updated on the actual git hub page iam not sure why.
![screenshot 3](https://user-images.githubusercontent.com/46300563/52743034-22b76900-2fa7-11e9-9a99-d077d8418394.png)

**Comment by iarobinson** [comment]
@delagulater88 - Could you please get a plugin called Loom and make a screencast of your progress. Let me know where you are and what your issue is with pushing up your code? Good Luck!
