### ISSUE TITLE
Create an individual page for lessons

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#20]
- [x] Create a page per lesson (currently there are three lessons)
    - [x] Lesson 1  - Introduce Yourself
    - [x] Lesson 2 - Add your Name to Collaborators Index Page
    - [x] Lesson 3 - Create your collaborator page and link to it via your name on the index page

Currently, the three lessons are on the index page:

<img width="1202" alt="screen shot 2019-02-14 at 9 12 28 am" src="https://user-images.githubusercontent.com/7991933/52804326-d3217d80-3038-11e9-8848-943422b7d2e8.png">

You'll want to:
- [x] Create a folder called `lessons`
- [x] Add html file called `lesson1.html' to the lessons folder
- [x] Add html file called `lesson2.html' to the lessons folder
- [x] Add html file called `lesson3.html' to the lessons folder
- [x] Copy the video embed and the content from the index.html file which corresponds to each lesson and have it displaying in each individual page

You'll be able to check you work by visiting `lessons/lesson1.html` in your browser

Good luck!

**Comment by cjtabaldo** [comment]
yo @makromikro how is this coming along?

**Comment by makromikro** [comment]
I think it is already there :)

**Comment by cjtabaldo** [comment]
it is lol i was hella late

**Comment by iarobinson** [comment]
@cjtabaldo @makromikro Who's on this one? I want to know so we don't duplicate the work...

It looks like @makromikro is the assigned one, so I'm fine with him taking it on.

**Comment by cjtabaldo** [comment]
@iarobinson yeah I didnt touch it mybad still getting the hang of all of this.

**Comment by iarobinson** [comment]
@makromikro This one is still a good one for you to take on:

<img width="1357" alt="screen shot 2019-02-19 at 1 32 53 pm" src="https://user-images.githubusercontent.com/7991933/53049216-76183400-344b-11e9-8080-dc26946d6584.png">

In order to complete this one, think about what you would want the page to look like if you were coming to this site for the first time. You're probably a young programmer learning to use git. We want the table of contents right there with Step #1 being super easy and obvious to find.

**Comment by makromikro** [comment]
@iarobinson are we talking about something like this?
![usefulprogrammer](https://user-images.githubusercontent.com/46354335/53432921-72dbf580-39c1-11e9-918a-6592bbb25129.jpg)

When I first come to the page what I would like to see, as a beginner, is a short explanation of what we are doing here. 

Is it enough to have the video and the collaborators on the first page and do the rest with the nav bar?

**Comment by iarobinson** [comment]
Hey @makromikro - I've basically trimmed down the extent of this project in the latest version. For now, I'm just closing this as we don't need it.
