### ISSUE TITLE
Linked your collaborator page properly

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#30]
Hey @cjtabaldo  
Currently, when I click your collaborator link, I get a 404 page error:

<img width="1211" alt="screen shot 2019-02-18 at 6 35 35 pm" src="https://user-images.githubusercontent.com/7991933/52986277-0bfc8200-33ac-11e9-94b7-402b02630ef7.png">

You'll want to fix this by editing the index.html page where you have linked out to your collaborator page.

**Comment by cjtabaldo** [comment]
@iarobinson Yeah, I saw that.... lol, I am working on that right now. I also wanted to know am I merging my branch correctly to the master? just thought I ask, I saw your response about ppl merging master.

**Comment by iarobinson** [comment]
I think you've got it working! I'll close this issue for now.
