### ISSUE TITLE
Table of Content Page *new*

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#34]
@cjtabaldo , your mission, should you choose to accept it, is to create a table of content page.

It should:
- [x] Match the layout and look of the index page
- [x] Link to the individual lesson pages
- [x] Be mobile responsive ([Use the CSS from Skeleton which is already in the repo](http://getskeleton.com/))
- [x] The index page should link to the table of content page
- [x] The table of content page should link to the index page

If you're not interested in giving this one a try, please un-assign yourself using the `Assignees` gear box on the right.

God speed!

**Comment by cjtabaldo** [comment]
@iarobinson Thanks I will give it my best.
