### ISSUE TITLE
Fix your collaborator page

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#39]
Hey @delagulater88 - Good job with your page. but it needs a bit of cleaning up. :D  Great work my man!

<img width="1175" alt="screen shot 2019-02-21 at 8 42 03 pm" src="https://user-images.githubusercontent.com/7991933/53220414-4159d780-3619-11e9-92b4-3c0d6b2ace9d.png">

**Comment by delagulater88** [comment]
Thanks Ian  :)  ... Ill get right on it...

**Comment by iarobinson** [comment]
I fixed it for you for the time being. Closing this meow
