### ISSUE TITLE
Long term application decision discussion

### ISSUE THREAD

**Issue by ianrobinson1984** [iarobinson/learn-to-be-a-useful-programmer#4]
My initial thoughts:
- Boostrap
- NodeJS
- ExpressJS

I'm thinking of basing it on [MegaBoiler plate](https://github.com/sahat/megaboilerplate).

I'd like to do this despite the fact that I'm a big fan of Ruby on Rails. What do you guys think?

**Comment by makromikro** [comment]
Can you open 'Long term application decision discussion' a little? Is it the README file they have?

**Comment by iarobinson** [comment]
Closing this issue as the subject should be handled in the slack group.
