### ISSUE TITLE
Need a series of lessons for especially young programmers to learn basics

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#7]
It would be good if we could have each collaborator earn check marks on their collaborator page as they complete various HTML, CSS and JavaScript challenges.

This might need to be wrapped into the overall application, but maybe there is a way to validate things using static pages.

Let me know if you're interested in this.

**Comment by makromikro** [comment]
Something similar to freecodecamp system?

**Comment by cjtabaldo** [comment]
That will be dope.

**Comment by iarobinson** [comment]
Yeah. I'm working on building a webApp now. Once you guys move through this process, you can get started with helping me build the application.

[You can track my work here:](https://github.com/iarobinson/usefulProgrammer)

https://github.com/iarobinson/usefulProgrammer
