### ISSUE TITLE
Develop a Table of Context for `trust-the-process` documents

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#8]
We currently have a folder called `Trust the Process`.

We need to develop a way of indexing this so new coders can begin their journey by completing a single chapter at a time.

I've already added the [first step](https://github.com/iarobinson/learn-to-be-a-useful-programmer/blob/master/trust-the-process/first-step.html).

## To Do:
- [ ] Add link from main index page to the first-step page
- [ ] Develop the look of the index page to have a cool table of contents look

**Comment by iarobinson** [comment]
The pages should be created in a PR related to this:

## Create an individual page for lessons #20 

Whoever develops the table of contents will just link to the pages developed in the link above.

**Comment by makromikro** [comment]
@iarobinson This reminded me the documentation page structure. But we don't want something like this right? Or do we? Here:
![image](https://user-images.githubusercontent.com/46354335/53433671-d6b2ee00-39c2-11e9-9a87-fd2f902afc7c.png)

**Comment by makromikro** [comment]
Here is a link to freecodecamp example of the documentation page: https://codepen.io/freeCodeCamp/full/NdrKKL
