### ISSUE TITLE
Create Reusable Navigation

### ISSUE THREAD

**Issue by iarobinson** [iarobinson/learn-to-be-a-useful-programmer#9]
Currently, each page has to be written by hand. It would be nice if we could have the same `<head>` code for each page on the site.

I know `node` will take care of this in the future. For now, is there a way for us to script it?

**Comment by makromikro** [comment]
Is there a way to do it in js maybe? I can look for it. Maybe bootstrap?

**Comment by iarobinson** [comment]
I'm fine to switch to bootstrap. I'm not sure what JS would be best for this, but if you can do it without a library, that would be ideal.

**Comment by makromikro** [comment]
I found Cakephp and js mustache npm for this but these are all libraries. I found out only bootstrap wouldn't be enough, we need to use an engine for it. Is this ok if I look deeper into what I found or do you think I should look for another way to do it?

**Comment by iarobinson** [comment]
I think we're going to move away from this as it doesn't make sense to have reusable navigation the way I see the direction of this project now.
